// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF4SuW09XDf4FMS7J8EeaIX4HO3ecPyYE',
    appId: '1:425634001546:web:8759190c1caaa3a9107373',
    messagingSenderId: '425634001546',
    projectId: 'binge-1fe39',
    authDomain: 'binge-1fe39.firebaseapp.com',
    storageBucket: 'binge-1fe39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUG_VysEsKId22RkB2JVwad7HfxxrMMA4',
    appId: '1:425634001546:android:e775d9f94e750c41107373',
    messagingSenderId: '425634001546',
    projectId: 'binge-1fe39',
    storageBucket: 'binge-1fe39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF_SQyIqp1UVJj_M1BxtSd26SiHL_PB0U',
    appId: '1:425634001546:ios:a3adcf08e5dd4b32107373',
    messagingSenderId: '425634001546',
    projectId: 'binge-1fe39',
    storageBucket: 'binge-1fe39.appspot.com',
    iosBundleId: 'com.example.binge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF_SQyIqp1UVJj_M1BxtSd26SiHL_PB0U',
    appId: '1:425634001546:ios:a3adcf08e5dd4b32107373',
    messagingSenderId: '425634001546',
    projectId: 'binge-1fe39',
    storageBucket: 'binge-1fe39.appspot.com',
    iosBundleId: 'com.example.binge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF4SuW09XDf4FMS7J8EeaIX4HO3ecPyYE',
    appId: '1:425634001546:web:a91cc1b9a5a564f1107373',
    messagingSenderId: '425634001546',
    projectId: 'binge-1fe39',
    authDomain: 'binge-1fe39.firebaseapp.com',
    storageBucket: 'binge-1fe39.appspot.com',
  );
}
