// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARtUFl10Isp7oQIEpgMAOHgBt029FHKCI',
    appId: '1:425639538301:web:124c1f933892bfdca90b14',
    messagingSenderId: '425639538301',
    projectId: 'bingebros-2b3bc',
    authDomain: 'bingebros-2b3bc.firebaseapp.com',
    storageBucket: 'bingebros-2b3bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUax4qyNRz8fmCXFxB5kY7V8-BYO2rOdA',
    appId: '1:425639538301:android:444c72f453522cdba90b14',
    messagingSenderId: '425639538301',
    projectId: 'bingebros-2b3bc',
    storageBucket: 'bingebros-2b3bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXDMoD6LzeNKAC4B6z81FHEWZishUsEZ4',
    appId: '1:425639538301:ios:331c7b120470b6f4a90b14',
    messagingSenderId: '425639538301',
    projectId: 'bingebros-2b3bc',
    storageBucket: 'bingebros-2b3bc.appspot.com',
    iosBundleId: 'com.example.bingebros',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXDMoD6LzeNKAC4B6z81FHEWZishUsEZ4',
    appId: '1:425639538301:ios:331c7b120470b6f4a90b14',
    messagingSenderId: '425639538301',
    projectId: 'bingebros-2b3bc',
    storageBucket: 'bingebros-2b3bc.appspot.com',
    iosBundleId: 'com.example.bingebros',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARtUFl10Isp7oQIEpgMAOHgBt029FHKCI',
    appId: '1:425639538301:web:b19d1da6fc4b5c1ea90b14',
    messagingSenderId: '425639538301',
    projectId: 'bingebros-2b3bc',
    authDomain: 'bingebros-2b3bc.firebaseapp.com',
    storageBucket: 'bingebros-2b3bc.appspot.com',
  );
}
