// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_api_key.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: FirebaseApiKeys.webApiKey,
    appId: FirebaseApiKeys.appIdWeb,
    messagingSenderId: FirebaseApiKeys.messagingSenderId,
    projectId: FirebaseApiKeys.projectId,
    authDomain: FirebaseApiKeys.authDomain,
    storageBucket: FirebaseApiKeys.storageBucket,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: FirebaseApiKeys.androidApiKey,
    appId: FirebaseApiKeys.appIdAndroid,
    messagingSenderId: FirebaseApiKeys.messagingSenderId,
    projectId: FirebaseApiKeys.projectId,
    storageBucket: FirebaseApiKeys.storageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: FirebaseApiKeys.iosApiKey,
    appId: FirebaseApiKeys.appIdIos,
    messagingSenderId: FirebaseApiKeys.messagingSenderId,
    projectId: FirebaseApiKeys.projectId,
    storageBucket: FirebaseApiKeys.storageBucket,
    iosBundleId: FirebaseApiKeys.iosBundleId,
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: FirebaseApiKeys.iosApiKey,
    appId: FirebaseApiKeys.appIdIos,
    messagingSenderId: FirebaseApiKeys.messagingSenderId,
    projectId: FirebaseApiKeys.projectId,
    storageBucket: FirebaseApiKeys.storageBucket,
    iosBundleId: FirebaseApiKeys.iosBundleId,
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: FirebaseApiKeys.webApiKey,
    appId: FirebaseApiKeys.appIdWindows,
    messagingSenderId: FirebaseApiKeys.messagingSenderId,
    projectId: FirebaseApiKeys.projectId,
    authDomain: FirebaseApiKeys.authDomain,
    storageBucket: FirebaseApiKeys.storageBucket,
  );
}
