name: binge
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  http: ^1.2.2 # This is for making HTTP requests
  swipe_cards: 2.0.0+1  # Add this package for swipe functionality
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.1.0
  concentric_transition: ^1.0.3
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  fluttermoji: ^1.0.2
  google_sign_in: ^6.2.1
  intl_phone_number_input: ^0.7.4
  lottie: ^3.1.2
  package_info_plus: 8.0.2
  pinput: ^5.0.0
  provider: ^6.0.3
  shared_preferences: ^2.2.3
  sign_in_button: ^3.2.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/Wa5v8hxVSb.json
    - assets/google_logo.png
    - assets/avatar1.png
    - assets/avatar2.png
    - assets/avatar3.png
    - assets/avatar4.png
    - assets/avatar5.png
    - assets/avatar6.png
    - assets/avatar7.png
    - assets/avatar8.png
    - assets/anime_animation.json
    - assets/books_animation.json
    - assets/gaming_animation.json
    - assets/introduction_animation.json
    - assets/movie_animation.json
    - assets/bg.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"